name: Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  publish:
    name: "Publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Pixi Python Project
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.28.2
          cache: true
          environments: dev  # separate by spaces; only using the dev environment to build
      
      - name: Install twine from conda-forge (globally as to not interfere)
        run: pixi global install twine
      
      - name: Build package
        run: pixi run -e dev build
      
      - name: Publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
